config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new' 
  get 'users/edit'
  get 'users/show'

	root 'sessions#new'

	resources :item
	resources :categories
	get "/item/busca " => "item#busca", as: :busca_item
   

	resources :users
    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete 'sign_out'  => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :category_items
	has_many :items, through: :category_items 
	validates_presence_of :nome
end

app/models/category_item.rb
	class CategoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :category_items
	has_many :categories , through: :category_items
	validates_presence_of :nome, :descricao, :preco
	validates :nome, length: {minimum: 5, maximum:20}

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :nome, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authorize
      unless logged_in?
   	   redirect_to root_url
      end
  end
    def correct_user?
      @user = User.find(params[:id])
	    unless current_user == @user
            redirect_to users_path
        end
     end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categorias = Category.all
	end
	
	def show
		@categoria = Category.find(params[:id])
	end

	def new
		@categoria = Category.new
	end

	def create
		@categoria = Category.new(category_params)
		if @categoria.save
			redirect_to categories_path
		else
			render 'new'	
		end	
	end
	def destroy

	end

	def edit

	end

	def update
	end	

	private	

	def category_params
		params.require(:category).permit(:nome)	
	end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController

	def index
		@itens = Item.all.order :nome
	end	

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end


	def create
	   @item =  Item.new(items_params)
	   if @item.save
	   	flash[:notice]= "Item feito com sucesso"
	   	redirect_to root_path
	   else
	   	render 'new'	
	   end

	end	

	def busca
	end

	def destroy

	end

	def edit

	end

	def update
	end	

	private 

	def items_params
		params.require(:item).permit(:nome, :descricao,:preco, category_ids:[] )
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

 	before_action :block_access, except: [:destroy]
    def create  
		@user = User.find_by(email: params[:session][:email].downcase)
		if @user && @user.authenticate(params[:session][:password])
		    sign_in(@user)
  			redirect_to @user
        else
            render 'new'
        end
    end

    def destroy
        sign_out
      	redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_action :authorize, except: [:new, :create]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to @user , notice: "Usuário criado com sucesso!"
  	else
  		render action: :new
  	end
  
  end
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
	end

	 def edit
      @user = User.find(params[:id]) 
    end
   
    def update
      @user = User.find(params[:id]) 
      if @user.update_attributes(user_params)
        redirect_to users_path
      else
        render action: :edit
      end
    end
   
    def destroy
      @user = User.find(params[:id]) 
      @user.destroy
      sign_out
      redirect_to root_path
    end

  private
  	
  def user_params
  	params.require(:user).permit(:nome, :email, :password, :password_confirmation)
  end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in
	    session[:user_id] = @user.id
	end
	def current_user
	   @current_user ||= User.find_by(id: session[:user_id])
	end
	def block_access
		if current_user.present?
		    redirect_to users_path
  		end
	end
	def logged_in?
      !current_user.nil?
    end
    def sign_out
		session.delete(:user_id)
    	@current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
	<h1 align="center">CATEGORIAS</h1><br/>
	<table class="table">
		<thead>
			<tr>
				<th>Nome</th>
			</tr>
		</thead>
		<tbody>
			<% @categorias.each do |categorias| %>
				<tr>
					<td><%= categorias.nome%></td>
				</tr>
			<%end%>	
		</tbody>
	</table>

	<%= link_to "ADD" , new_category_path , class:"btn btn-primary" %>

app/views/categories/new.html.erb
 <%= form_for @categoria , url: categories_path do |f| %>

	Nome
	<%= f.text_field :nome %><br/>    


	<%= f.submit %>    
<%end%>

	<%= link_to" back", categories_path, class:"btn btn-primary btn-xs" %>

app/views/item/index.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success" role="alert">
		<%= flash[:notice] %>
		
	</div>
<% end %>

	<h1 align="center">ITEM</h1><br/>
	<table class="table">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Descrição</th>
				<th>Preço(em R$)</th>
			</tr>
		</thead>
		<tbody>
			<% @itens.each do |itens| %>

				<tr>
					<td><%= itens.nome%></td>
					<td><%= itens.descricao%></td>
					<td><%= itens.preco%></td>
				</tr>
			<%end%>	
		</tbody>
	</table>

	<%= link_to "ADD item" , new_item_path , class:"btn btn-primary btn-xs" %>
	<%= link_to "ADD categoria" , categories_path , class:"btn btn-primary btn-xs" %>

app/views/item/new.html.erb
	
<% @item.errors.full_messages.each do |message| %>
	<div class="alert alert-danger" role="alert">
		<% message %>	
	</div>
<% end %>


 <%= form_for @item , url: item_index_path do |f| %>

	Nome
	<%= f.text_field :nome %><br/>    

	Descrição
	<%= f.text_area :descricao %><br/>   

	Categoria
	<div>
		<%= f.collection_check_boxes(:category_ids, Category.all, :id, :nome) do |category| %>
  			<%= category.label { category.check_box } + category.text %>
		<% end %>
	</div> 

	Preço
	<%= f.number_field :preco, step: 0.01, min: 0 %><br/>    
		
	<%= f.submit %>    
<%end%>

	<%= link_to" back", item_index_path, class:"btn btn-primary btn-xs" %>

app/views/layouts/ _header.html.erb
  <header>
    <div>
      <nav>
        <ul>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li>
              <ul>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li>
                  <%= link_to "Log out", sign_out_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", root_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerDash</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "DinnerDash", brand_link: root_path  do  %>
    	<% form_tag busca_item_path, method: :get, class: "navbar-form navbar-right" do %>
          <div class="form-group">
            <%=  text_field_tag :nome, nil, class: "form-control"   %>
            <%= button_to "Buscar", nil, class: "btn btn-defaut" %>
          </div>
      <% end %>    
   <!-- render 'layouts/header' obs: n estava conseguindo funcionar--> 
          <div class="form-group">
          <nav>
            <ul>
              <% if logged_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li>
                  <ul>
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", '#' %></li>
                    <li>
                      <%= link_to "Log out", sign_out_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <div class="navbar-form navbar-right"  >
               
                  <%= link_to "Log in", sign_in_path, class:"btn btn-success" %></div>
      

              <% end %>
            </ul>
          </nav>
        </div>
    
  
    <% end %> 

    <div class="container">

      <%= yield %>
  		
  	</div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f|  %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<div class="alert-error">
				O formulário contém <%= pluralize(@user.errors.count, "erro")  %>
			</div>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
	            	<li><%= msg %></li>
	            <% end %>
			</ul>	
		</div>
	<% end %>

	<div class="field">
          <%= f.label :nome %>
          <%= f.text_field :nome %>
      </div>
      <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email %>
      </div>
      <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password %>
      </div>
      <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
      </div>
      <div class="actions">
          <%= f.submit "Cadastrar"%>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= User Settings %></h1>
<%= render 'form' %>

<ul>
  <li><%= link_to "Edit", edit_user_path(current_user) %></li>
  <li><%= link_to "Delete", @user, method: :delete%></li>
</ul>  

app/views/users/index.html.erb
  <h1> Users </h1>
  <table>
     <thead>
       <tr>
         <th>Name</th>
         <th>Email</th>
         <th></th>
       </tr>
     </thead>
     <tbody>
       <% @users.each do |user| %>
         <tr>
           <td><%= user.nome %></td>
           <td><%= user.email %></td>
           <td><%= link_to "Show", user %></td>
         </tr>
      <%end%>
    </tbody>
 </table>

app/views/users/new.html.erb
  <h1>Sign Up</h1>

  <%= render 'form' %>

app/views/users/show.html.erb
<html>
      <body>
          <h3> Perfil de <%= @user.nome %> </h3>
          <%= @user.email %>
          <% if current_user == @user %>
             <ul>
                 <li><%= link_to "Edit", edit_user_path(current_user) %></li>
                 <li><%= link_to "Delete", @user, method: :delete%></li>
             </ul>
          <%end%>
      </body>
</html>